# docker-compose.yml - 简化版本，专注 Vercel 数据库
version: "3.8"

services:
  # 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-backend
    restart: unless-stopped
    ports:
      - "9191:9191"
    environment:
      # 数据库配置
      - DB_MODE=vercel
      - VERCEL_POSTGRES_URL=${VERCEL_POSTGRES_URL}

      # 应用配置
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_PORT=9191
      - GIN_MODE=release
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}

      # 文件配置
      - UPLOAD_PATH=/app/uploads
      - MAX_IMAGE_SIZE=${MAX_IMAGE_SIZE:-10485760}
      - MAX_DOCUMENT_SIZE=${MAX_DOCUMENT_SIZE:-52428800}
      - MAX_USER_STORAGE=${MAX_USER_STORAGE:-524288000}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - notes-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:9191/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: notes-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge
