server:
  port: 8080
  mode: debug # debug, release

database:
  host: localhost
  port: 5432
  user: notes_user
  password: notes_password
  dbname: notes_db
  sslmode: disable

jwt:
  secret: your-super-secret-jwt-key-change-this-in-production
  expire_hours: 24

file:
  upload_path: ./uploads
  max_image_size: 10485760 # 10MB
  max_document_size: 52428800 # 50MB
  max_user_storage: 524288000 # 500MB
  allowed_image_types:
    - jpg
    - jpeg
    - png
    - gif
    - webp
  allowed_document_types:
    - pdf
    - doc
    - docx
    - xls
    - xlsx

backup:
  enabled: true
  path: ./backup
  schedule: "0 2 * * *" # 每天凌晨2点
  keep_days: 30

log:
  level: info
  file: ./logs/app.log
  max_size: 100 # MB
  max_age: 30 # days
  max_backups: 3
